"""
Short English display names for common merchants (charts & tables).
Falls back to Google Translate when no mapping exists.
"""
import math

# Exact merchant strings from exports (highest priority)
EXACT_NAMES: dict[str, str] = {
    # Eating out & coffee
    "麦当劳": "McDonald's",
    "全家": "FamilyMart",
    "萨莉亚": "Saizeriya",
    "萨莉亚南京东路四店": "Saizeriya",
    "喜茶": "HEYTEA",
    "霸王茶姬": "CHAGEE",
    "蜜雪冰城": "Mixue",
    "蜜雪冰城934055店": "Mixue",
    "达美乐": "Domino's",
    "必胜客": "Pizza Hut",
    "喜士多": "C-Store",
    "喜士多(高青西店)": "C-Store",
    "喜士多（济明门市）": "C-Store",
    "luckin coffee": "Luckin Coffee",
    "卯时六点半": "Maoshi 6:30",
    "蘇小柳": "Su Xiaoliu",
    "喝清喝理（上海）餐饮管理有限公司": "INS",
    "正三熙by韩国街小木屋烤肉": "Jeong Sam Hee",
    "小满手工粉": "Xiaoman Noodles",
    "美淑家·韩国料理·石锅拌饭": "Mei Shujia Korean",
    "饿梨酱Hey Guac·美洲活力西餐": "Hey Guac",
    "YogurtDay酸奶（世博天地店）": "YogurtDay",
    "马永胜牛肉面": "Ma Yongsheng Noodles",
    "济明路蘭州牛肉面（百热客）": "Baireke Lanzhou Noodles",
    "昆仑唐府兰州牛肉面（后滩店）": "Kunlun Tangfu",
    "昆仑唐府兰州纯汤牛肉面": "Kunlun Tangfu",
    "上海市豹喵酒吧": "Meow Bar",
    "橘柚梧桐": "Juyou Wutong",
    # Transport
    "滴滴出行": "DiDi",
    "高德打车": "Amap",
    "哈啰出行": "HelloBike",
    "春秋航空": "Spring Airlines",
    "上海地铁": "Shanghai Metro",
    "上海申通地铁资产经营管理有限公司": "Shanghai Metro",
    "上海公共交通卡股份有限公司": "Shanghai Transit Card",
    "浦东机场": "Pudong Airport",
    # Shopping & platforms
    "美团": "Meituan",
    "美团平台商户": "Meituan",
    "淘宝平台商户": "Taobao",
    "淘宝闪购": "Taobao",
    "拼多多": "Pinduoduo",
    "拼多多平台商户": "Pinduoduo",
    "得物-得到美好事物": "Dewu",
    "得物APP平台商户": "Dewu",
    "无印良品MUJI": "MUJI",
    "名创优品": "MINISO",
    "荟选集市后滩店": "H-Life",
    "APIO艾彼悠": "APIO",
    "杂物社": "Nine Wood Zakka",
    "杜福睿(上海)商业有限公司": "DFS",
    "淘天物流科技有限公司": "Taotian Logistics",
    "KKV": "KKV",
    "绿联**店": "UGREEN",
    # Institutions & services
    "上海纽约大学": "NYU Shanghai",
    "上海一网通办缴费平台": "SH Gov Online Pay",
    "上海国际旅行卫生保健中心": "Shanghai Travel Health",
    "中国移动": "China Mobile",
    "中石化上海": "Sinopec",
    "好德": "Alldays",
    "统一超商(上海)便利有限公司": "7-ELEVEN",
    "沪浙7-ELEVEN": "7-ELEVEN",
    "7-ELEVEN上海(嘉里)": "7-ELEVEN",
    "7-11浙江宁波": "7-ELEVEN",
    "SUBWAY": "Subway",
    "POPEYES": "Popeyes",
    "LAWSON": "Lawson",
    # Transfers / P2P
    "个人收款尼彦兵": "P2P Transfer",
    # Vending / devices
    "荣康倍儿爽共享按摩椅": "Massage Chair",
    "乐科智控": "Lecco Vending",
    "友宝昂莱": "Ubox Vending",
    "大象智贩": "Elephant Vending",
    "聆动": "Lingdong Vending",
    "聆动电子科技": "Lingdong Vending",
    # Local entities (shortened legal names)
    "上海蕤盛工贸": "Ruisheng Trading",
    "上海都畅数字技术有限公司": "Duchang Digital",
    "上海饱猫餐饮管理有限公司": "Baomao Catering",
    "上海谱墨品牌管理有限公司": "Pumo Brands",
    "上海芸译餐饮有限公司": "Yunyi Catering",
    "上海优悠生活商业管理有限公司": "Youyou Life",
    "上海英和企业管理有限公司": "Yinghe Enterprise",
    "初易（上海）餐饮管理有限公司": "Chuyi Catering",
    "卓联（上海）餐饮服务有限公司": "Zhuolian Catering",
    "叶浦都餐饮管理（上海）有限公司": "Yepudu Catering",
    "昔客堡（上海）餐饮服务有限公司": "Xikebao Catering",
    "上海檀檀之家餐饮管理有限公司": "Tantan Catering",
    "久鼎餐饮管理": "Jiuding Catering",
    "宁波市鄞州首南芳霞饭店": "Fangxia Restaurant",
    "广州市玩客游乐设备有限公司": "Wanke Amusement",
    "广州大头贴": "Guangzhou Photo Booth",
    "JUNGLEplus广州动漫新城店": "JUNGLEplus",
    "大黄鹅": "Big Yellow Goose",
    "鹈鹕镇大王": "Pelican Town",
    "高青西门市": "Gaoqing Store",
    "ao**店": "Online Store",
    "wa**店": "Online Store",
    "恒品**店": "Online Store",
    "雅纳晟嘉影文化传播（杭州）有限公司": "Yana Film",
    "云上智造（上海）科技发展有限公司": "Yunshang Tech",
    "上海香雪海国际贸易有限公司": "Xiangxuehai Trading",
    "🔥战🙏狼🔥": "P2P Transfer",
}

# First matching substring wins — list more specific patterns before broad ones.
SUBSTRING_RULES: list[tuple[str, str]] = [
    # E-commerce & platforms
    ("淘宝闪购", "Taobao Flash"),
    ("淘宝平台", "Taobao"),
    ("淘宝", "Taobao"),
    ("淘天物流", "Taotian Logistics"),
    ("天猫", "Tmall"),
    ("京东", "JD.com"),
    ("拼多多", "Pinduoduo"),
    ("闲鱼", "Xianyu"),
    ("1688", "1688.com"),
    ("菜鸟", "Cainiao"),
    ("得物", "Dewu"),
    ("美团", "Meituan"),
    ("饿了么", "Ele.me"),
    ("京东便利店", "JD Convenience"),
    ("京东物流", "JD Logistics"),
    ("京东秒送", "JD Instashopping"),
    ("唯品会", "Vipshop"),
    ("抖音", "Douyin"),
    ("快手", "Kuaishou"),
    ("小红书", "Xiaohongshu"),
    ("京喜", "Jingxi"),
    ("小米有品", "Xiaomi Youpin"),
    ("网易严选", "NetEase Yanxuan"),
    # Ride-hail & maps
    ("滴滴出行", "DiDi"),
    ("滴滴", "DiDi"),
    ("高德打车", "Amap"),
    ("高德", "Amap"),
    ("哈啰出行", "HelloBike"),
    ("哈啰", "HelloBike"),
    ("曹操出行", "CaoCao Mobility"),
    ("T3出行", "T3 Chuxing"),
    ("嘀嗒出行", "Dida"),
    ("青桔单车", "Qingju Bike"),
    ("青桔", "Qingju Bike"),
    ("摩拜单车", "Mobike"),
    ("摩拜", "Mobike"),
    ("美团单车", "Meituan Bike"),
    ("一嗨租车", "eHi Car Rental"),
    ("神州租车", "CAR Inc."),
    # Fast food & coffee chains
    ("汉堡王", "Burger King"),
    ("麦当劳", "McDonald's"),
    ("肯德基", "KFC"),
    ("必胜客", "Pizza Hut"),
    ("达美乐", "Domino's"),
    ("萨莉亚", "Saizeriya"),
    ("瑞幸咖啡", "Luckin Coffee"),
    ("瑞幸", "Luckin Coffee"),
    ("luckin coffee", "Luckin Coffee"),
    ("星巴克", "Starbucks"),
    ("喜茶", "HEYTEA"),
    ("霸王茶姬", "CHAGEE"),
    ("蜜雪冰城", "Mixue"),
    ("茶百道", "Chabaidao"),
    ("古茗", "Guming"),
    ("奈雪", "Nayuki"),
    ("沪上阿姨", "Auntea Jenny"),
    ("书亦烧仙草", "Shuyi Tealicious"),
    ("库迪咖啡", "Cotti Coffee"),
    ("库迪", "Cotti Coffee"),
    ("Manner咖啡", "MANNER Coffee"),
    ("Manner", "MANNER Coffee"),
    ("M Stand", "M Stand"),
    ("Tims咖啡", "Tims Coffee"),
    ("甜啦啦", "Tianlala"),
    ("益禾堂", "Yihotang"),
    ("茶颜悦色", "Cha Yan Yuese"),
    ("CoCo都可", "CoCo"),
    ("1点点", "alittle Tea"),
    ("一点点", "alittle Tea"),
    ("SUBWAY", "Subway"),
    ("POPEYES", "Popeyes"),
    # Casual dining chains
    ("海底捞", "Haidilao"),
    ("吉野家", "Yoshinoya"),
    ("味千拉面", "Ajisen Ramen"),
    ("味千", "Ajisen Ramen"),
    ("真功夫", "Real Kung Fu"),
    ("老娘舅", "Laoniangjiu"),
    ("西贝莜面村", "Xibei"),
    ("西贝", "Xibei"),
    ("太二酸菜鱼", "Tai Er"),
    ("正新鸡排", "Zhengxin Chicken"),
    ("华莱士", "Wallace"),
    ("德克士", "Dicos"),
    ("塔斯汀", "Tasiting"),
    ("塔可贝尔", "Taco Bell"),
    ("黄记煌", "Huang Ji Huang"),
    ("小肥羊", "Little Sheep"),
    ("乡村基", "Country Style Cooking"),
    ("大米先生", "Da Mi Xian Sheng"),
    ("老乡鸡", "Laoxiangji"),
    ("杨国福麻辣烫", "Yang Guofu Malatang"),
    ("杨国福", "Yang Guofu Malatang"),
    ("张亮麻辣烫", "Zhang Liang Malatang"),
    ("和府捞面", "He Fu Noodle"),
    ("遇见小面", "Meet Noodle"),
    ("紫燕百味鸡", "Ziyan Braised Chicken"),
    ("袁记云饺", "Yuan's Dumplings"),
    ("沙县小吃", "Shaxian Snacks"),
    ("九毛九", "Jiumaojiu"),
    ("呷哺呷哺", "Xiabu Xiabu"),
    ("小龙坎", "Xiaolongkan"),
    ("大龙燚", "Dalongyi"),
    ("眉州东坡", "Meizhou Dongpo"),
    ("南京大牌档", "Nanjing Impressions"),
    ("外婆家", "Grandma's Home"),
    ("绿茶餐厅", "Green Tea Restaurant"),
    ("米村拌饭", "Mi Cun Bibimbap"),
    ("费大厨", "Fei Da Chu"),
    ("西少爷", "Bingz"),
    ("兰熊鲜奶", "Blue Bear"),
    ("永和大王", "Yonghe King"),
    ("大娘水饺", "Da Niang Dumplings"),
    ("巴奴毛肚火锅", "Mao Hotpot"),
    ("巴奴", "Mao Hotpot"),
    # Grocery & convenience
    ("山姆会员商店", "Sam's Club"),
    ("山姆会员店", "Sam's Club"),
    ("山姆", "Sam's Club"),
    ("开市客", "Costco"),
    ("叮咚买菜", "Dingdong Maicai"),
    ("美团买菜", "Meituan Grocery"),
    ("美团优选", "Meituan Select"),
    ("美宜佳", "Meiyijia"),
    ("昆仑好客", "Kunlun Convenience"),
    ("易捷便利店", "Easy Joy"),
    ("易捷", "Easy Joy"),
    ("天福便利店", "Tianfu"),
    ("天福", "Tianfu"),
    ("见福便利店", "Jianfu Convenience"),
    ("见福", "Jianfu Convenience"),
    ("红旗连锁", "Hongqi Chain"),
    ("便利蜂", "Bianlifeng"),
    ("芙蓉兴盛", "Furong Xingsheng"),
    ("唐久便利", "Tangjiu"),
    ("唐久", "Tangjiu"),
    ("可的便利店", "Kedi"),
    ("可的", "Kedi"),
    ("良友金伴", "Liangyou"),
    ("良友", "Liangyou"),
    ("十足便利店", "Shizu Convenience"),
    ("之上便利店", "Shizu Convenience"),
    ("十足", "Shizu Convenience"),
    ("好特卖", "Hotmaxx"),
    ("7-ELEVEN", "7-ELEVEN"),
    ("7-11", "7-ELEVEN"),
    ("统一超商", "7-ELEVEN"),
    ("全家", "FamilyMart"),
    ("喜士多", "C-Store"),
    ("罗森", "Lawson"),
    ("LAWSON", "Lawson"),
    ("好德", "Alldays"),
    ("奥乐齐", "ALDI"),
    ("盒马鲜生", "Freshippo"),
    ("盒马", "Freshippo"),
    ("永辉超市", "Yonghui Superstores"),
    ("永辉", "Yonghui Superstores"),
    ("大润发", "RT-Mart"),
    ("华润万家", "CR Vanguard"),
    ("华润", "CR Vanguard"),
    ("沃尔玛", "Walmart"),
    ("家乐福", "Carrefour"),
    ("屈臣氏", "Watsons"),
    ("万宁", "Mannings"),
    ("名创优品", "MINISO"),
    ("无印良品", "MUJI"),
    ("苏宁易购", "Suning"),
    ("苏宁", "Suning"),
    ("荟选集市", "Huixuan Market"),
    ("钱大妈", "Qdm"),
    ("百果园", "Pagoda"),
    ("泸溪河", "Luxihe"),
    ("良品铺子", "Bestore"),
    ("三只松鼠", "Three Squirrels"),
    ("周黑鸭", "Zhou Hei Ya"),
    ("绝味鸭脖", "Juewei"),
    ("绝味", "Juewei"),
    ("迪卡侬", "Decathlon"),
    ("宜家家居", "IKEA"),
    ("宜家", "IKEA"),
    ("优衣库", "UNIQLO"),
    ("泡泡玛特", "POP MART"),
    ("全棉时代", "Purcotton"),
    ("孩子王", "Kidswant"),
    ("小米之家", "Xiaomi"),
    ("小米", "Xiaomi"),
    ("华为", "Huawei"),
    ("苹果", "Apple"),
    ("国美电器", "Gome"),
    ("国美", "Gome"),
    ("万达影城", "Wanda Cinema"),
    ("万达", "Wanda"),
    ("中免日上", "CDF Sunrise"),
    ("中免", "CDF"),
    # Transport & travel
    ("上海申通地铁", "Shanghai Metro"),
    ("上海地铁", "Shanghai Metro"),
    ("申通地铁", "Shanghai Metro"),
    ("轨道交通", "Metro"),
    ("上海蕤盛工贸", "Shanghai Metro"),
    ("地铁", "Shanghai Metro"),
    ("公共交通卡", "Shanghai Transit Card"),
    ("浦东机场", "Pudong Airport"),
    ("春秋航空", "Spring Airlines"),
    ("中国东方航空", "China Eastern"),
    ("东方航空", "China Eastern"),
    ("南方航空", "China Southern"),
    ("国际航空", "Air China"),
    ("国航", "Air China"),
    ("12306", "China Railway"),
    ("铁路", "China Railway"),
    ("顺丰", "SF Express"),
    ("中通快递", "ZTO Express"),
    ("中通", "ZTO Express"),
    ("圆通速递", "YTO Express"),
    ("圆通", "YTO Express"),
    ("韵达快递", "Yunda Express"),
    ("韵达", "Yunda Express"),
    ("申通快递", "STO Express"),
    ("极兔速递", "J&T Express"),
    ("极兔", "J&T Express"),
    ("德邦快递", "Deppon"),
    ("德邦", "Deppon"),
    ("邮政EMS", "EMS"),
    ("EMS", "EMS"),
    ("携程", "Trip.com"),
    ("飞猪", "Fliggy"),
    ("同程旅行", "Tongcheng Travel"),
    ("同程", "Tongcheng Travel"),
    ("去哪儿", "Qunar"),
    ("华住酒店", "Huazhu Hotels"),
    ("华住", "Huazhu Hotels"),
    ("如家酒店", "Home Inn"),
    ("如家", "Home Inn"),
    ("锦江之星", "Jinjiang Inn"),
    ("锦江", "Jinjiang Inn"),
    ("亚朵酒店", "Atour"),
    ("亚朵", "Atour"),
    ("汉庭酒店", "Hanting Hotel"),
    ("汉庭", "Hanting Hotel"),
    ("全季酒店", "Ji Hotel"),
    ("全季", "Ji Hotel"),
    # Telecom & utilities
    ("中国移动", "China Mobile"),
    ("中国联通", "China Unicom"),
    ("中国电信", "China Telecom"),
    ("中石化", "Sinopec"),
    ("中石油", "PetroChina"),
    ("国家电网", "State Grid"),
    ("南方电网", "China Southern Power Grid"),
    # Institutions
    ("上海纽约大学", "NYU Shanghai"),
    ("纽约大学", "NYU"),
    ("一网通办", "SH Gov Online Pay"),
    ("国际旅行卫生保健", "Shanghai Travel Health"),
    # Retail & lifestyle
    ("杜福睿", "DFS"),
    ("杂物社", "Nine Wood Zakka"),
    ("APIO", "APIO"),
    ("蘇小柳", "Su Xiaoliu"),
    ("昆仑唐府", "Kunlun Tangfu"),
    ("喝清喝理", "Heqing Heli"),
    ("正三熙", "Jeong Sam Hee"),
    ("小满手工粉", "Xiaoman Noodles"),
    ("绿联", "UGREEN"),
    ("哔哩哔哩", "Bilibili"),
    ("B站", "Bilibili"),
    # Vending / shared devices
    ("友宝", "Ubox Vending"),
    ("共享按摩椅", "Massage Chair"),
    ("乐科智控", "Lecco Vending"),
    # P2P / transfers
    ("个人收款", "P2P Transfer"),
    ("**店", "Online Store"),
    # Entertainment
    ("爱奇艺", "iQIYI"),
    ("腾讯视频", "Tencent Video"),
    ("优酷", "Youku"),
    ("芒果TV", "Mango TV"),
    ("网易", "NetEase"),
    ("汽水音乐", "Qishui Music"),
]


def display_merchant(name: str) -> str:
    """Return a short English display name for a merchant."""
    if name is None:
        return ""
    if isinstance(name, float) and math.isnan(name):
        return ""
    text = str(name).strip()
    if not text:
        return text

    if text in EXACT_NAMES:
        return EXACT_NAMES[text]

    for pattern, label in SUBSTRING_RULES:
        if pattern in text:
            return label

    # Lazy import avoids circular load with translate.py (which imports this module).
    from translate import _sanitize_english, has_cjk, shorten, translate_to_english

    if not has_cjk(text):
        return text

    translated = translate_to_english(text)
    return shorten(_sanitize_english(translated, "Unknown merchant"), 28)


def add_display_names(df, source_col: str = "merchant", target_col: str = "merchant_display"):
    """Add a display-name column to a DataFrame copy."""
    out = df.copy()
    out[target_col] = out[source_col].map(display_merchant)
    return out


def aggregate_merchants(df, n: int = 12) -> "pd.DataFrame":
    """Sum spending by English display name."""
    import pandas as pd

    return (
        df.assign(merchant_display=df['merchant'].map(display_merchant))
        .groupby('merchant_display', as_index=False)['amount']
        .sum()
        .nlargest(n, 'amount')
    )
