-- Seed global merchant rules and initialize category function
-- Generated from src/merchant_categories.py::MERCHANT_CATEGORY_RULES

-- ========== SEED GLOBAL MERCHANT RULES ==========
INSERT INTO merchant_rules (user_id, merchant_pattern, category_name, source)
VALUES
  (NULL, '美团买菜', 'Groceries', 'global_seed'),
  (NULL, '美团优选', 'Groceries', 'global_seed'),
  (NULL, '叮咚买菜', 'Groceries', 'global_seed'),
  (NULL, '京东便利店', 'Groceries', 'global_seed'),
  (NULL, '山姆会员商店', 'Groceries', 'global_seed'),
  (NULL, '山姆会员店', 'Groceries', 'global_seed'),
  (NULL, '盒马鲜生', 'Groceries', 'global_seed'),
  (NULL, '永辉超市', 'Groceries', 'global_seed'),
  (NULL, '7-ELEVEN', 'Groceries', 'global_seed'),
  (NULL, '7-11', 'Groceries', 'global_seed'),
  (NULL, '统一超商', 'Groceries', 'global_seed'),
  (NULL, '见福便利店', 'Groceries', 'global_seed'),
  (NULL, '天福便利店', 'Groceries', 'global_seed'),
  (NULL, '可的便利店', 'Groceries', 'global_seed'),
  (NULL, '十足便利店', 'Groceries', 'global_seed'),
  (NULL, '之上便利店', 'Groceries', 'global_seed'),
  (NULL, '易捷便利店', 'Groceries', 'global_seed'),
  (NULL, '唐久便利', 'Groceries', 'global_seed'),
  (NULL, '绝味鸭脖', 'Groceries', 'global_seed'),
  (NULL, '良品铺子', 'Groceries', 'global_seed'),
  (NULL, '三只松鼠', 'Groceries', 'global_seed'),
  (NULL, '荟选集市', 'Groceries', 'global_seed'),
  (NULL, '山姆', 'Groceries', 'global_seed'),
  (NULL, '开市客', 'Groceries', 'global_seed'),
  (NULL, '盒马', 'Groceries', 'global_seed'),
  (NULL, '永辉', 'Groceries', 'global_seed'),
  (NULL, '大润发', 'Groceries', 'global_seed'),
  (NULL, '华润万家', 'Groceries', 'global_seed'),
  (NULL, '美宜佳', 'Groceries', 'global_seed'),
  (NULL, '昆仑好客', 'Groceries', 'global_seed'),
  (NULL, '易捷', 'Groceries', 'global_seed'),
  (NULL, '天福', 'Groceries', 'global_seed'),
  (NULL, '见福', 'Groceries', 'global_seed'),
  (NULL, '红旗连锁', 'Groceries', 'global_seed'),
  (NULL, '便利蜂', 'Groceries', 'global_seed'),
  (NULL, '芙蓉兴盛', 'Groceries', 'global_seed'),
  (NULL, '唐久', 'Groceries', 'global_seed'),
  (NULL, '可的', 'Groceries', 'global_seed'),
  (NULL, '良友金伴', 'Groceries', 'global_seed'),
  (NULL, '良友', 'Groceries', 'global_seed'),
  (NULL, '十足', 'Groceries', 'global_seed'),
  (NULL, '好特卖', 'Groceries', 'global_seed'),
  (NULL, 'ALDI', 'Groceries', 'global_seed'),
  (NULL, '奥乐齐', 'Groceries', 'global_seed'),
  (NULL, 'LAWSON', 'Groceries', 'global_seed'),
  (NULL, 'FamilyMart', 'Groceries', 'global_seed'),
  (NULL, '全家', 'Groceries', 'global_seed'),
  (NULL, '喜士多', 'Groceries', 'global_seed'),
  (NULL, '罗森', 'Groceries', 'global_seed'),
  (NULL, '好德', 'Groceries', 'global_seed'),
  (NULL, '沃尔玛', 'Groceries', 'global_seed'),
  (NULL, '家乐福', 'Groceries', 'global_seed'),
  (NULL, '钱大妈', 'Groceries', 'global_seed'),
  (NULL, '百果园', 'Groceries', 'global_seed'),
  (NULL, '泸溪河', 'Groceries', 'global_seed'),
  (NULL, '周黑鸭', 'Groceries', 'global_seed'),
  (NULL, '绝味', 'Groceries', 'global_seed'),
  (NULL, 'APIO', 'Groceries', 'global_seed'),
  (NULL, '大黄鹅', 'Groceries', 'global_seed'),
  (NULL, 'grocery', 'Groceries', 'global_seed'),
  (NULL, 'supermarket', 'Groceries', 'global_seed'),
  (NULL, 'mart', 'Groceries', 'global_seed'),
  (NULL, 'market', 'Groceries', 'global_seed'),
  (NULL, 'produce', 'Groceries', 'global_seed'),
  (NULL, 'vegetables', 'Groceries', 'global_seed'),
  (NULL, 'fruits', 'Groceries', 'global_seed'),
  (NULL, 'fruit', 'Groceries', 'global_seed'),
  (NULL, 'meat market', 'Groceries', 'global_seed'),
  (NULL, 'fish market', 'Groceries', 'global_seed'),
  (NULL, 'bakery', 'Groceries', 'global_seed'),
  (NULL, 'daily essentials', 'Groceries', 'global_seed'),
  (NULL, 'household items', 'Groceries', 'global_seed'),
  (NULL, 'bulk buy', 'Groceries', 'global_seed'),
  (NULL, 'wholesale', 'Groceries', 'global_seed'),
  (NULL, '蔬菜', 'Groceries', 'global_seed'),
  (NULL, '水果', 'Groceries', 'global_seed'),
  (NULL, '生鲜', 'Groceries', 'global_seed'),
  (NULL, '菜市场', 'Groceries', 'global_seed'),
  (NULL, '日用品', 'Groceries', 'global_seed'),
  (NULL, '家用', 'Groceries', 'global_seed'),
  (NULL, '批发', 'Groceries', 'global_seed'),
  (NULL, '食材', 'Groceries', 'global_seed'),
  (NULL, '粮油', 'Groceries', 'global_seed'),
  (NULL, '友宝', 'Groceries', 'global_seed'),
  (NULL, '乐科智控', 'Groceries', 'global_seed'),
  (NULL, '大象智贩', 'Groceries', 'global_seed'),
  (NULL, '聆动电子科技', 'Groceries', 'global_seed'),
  (NULL, '聆动', 'Groceries', 'global_seed'),
  (NULL, '美团单车', 'Transportation', 'global_seed'),
  (NULL, '上海申通地铁', 'Transportation', 'global_seed'),
  (NULL, '申通地铁', 'Transportation', 'global_seed'),
  (NULL, '上海地铁', 'Transportation', 'global_seed'),
  (NULL, '公共交通卡', 'Transportation', 'global_seed'),
  (NULL, '滴滴出行', 'Transportation', 'global_seed'),
  (NULL, '高德打车', 'Transportation', 'global_seed'),
  (NULL, '哈啰出行', 'Transportation', 'global_seed'),
  (NULL, '曹操出行', 'Transportation', 'global_seed'),
  (NULL, 'T3出行', 'Transportation', 'global_seed'),
  (NULL, '嘀嗒出行', 'Transportation', 'global_seed'),
  (NULL, '青桔单车', 'Transportation', 'global_seed'),
  (NULL, '摩拜单车', 'Transportation', 'global_seed'),
  (NULL, '一嗨租车', 'Transportation', 'global_seed'),
  (NULL, '神州租车', 'Transportation', 'global_seed'),
  (NULL, '中国东方航空', 'Transportation', 'global_seed'),
  (NULL, '东方航空', 'Transportation', 'global_seed'),
  (NULL, '南方航空', 'Transportation', 'global_seed'),
  (NULL, '春秋航空', 'Transportation', 'global_seed'),
  (NULL, '国际航空', 'Transportation', 'global_seed'),
  (NULL, '浦东机场', 'Transportation', 'global_seed'),
  (NULL, '轨道交通', 'Transportation', 'global_seed'),
  (NULL, '滴滴', 'Transportation', 'global_seed'),
  (NULL, '高德', 'Transportation', 'global_seed'),
  (NULL, '哈啰', 'Transportation', 'global_seed'),
  (NULL, '青桔', 'Transportation', 'global_seed'),
  (NULL, '摩拜', 'Transportation', 'global_seed'),
  (NULL, '地铁', 'Transportation', 'global_seed'),
  (NULL, '国航', 'Transportation', 'global_seed'),
  (NULL, '12306', 'Transportation', 'global_seed'),
  (NULL, '铁路', 'Transportation', 'global_seed'),
  (NULL, 'DiDi', 'Transportation', 'global_seed'),
  (NULL, 'ride', 'Transportation', 'global_seed'),
  (NULL, 'driver', 'Transportation', 'global_seed'),
  (NULL, 'passenger', 'Transportation', 'global_seed'),
  (NULL, 'ticket', 'Transportation', 'global_seed'),
  (NULL, 'fare', 'Transportation', 'global_seed'),
  (NULL, 'transit', 'Transportation', 'global_seed'),
  (NULL, 'train', 'Transportation', 'global_seed'),
  (NULL, 'bus', 'Transportation', 'global_seed'),
  (NULL, 'subway', 'Transportation', 'global_seed'),
  (NULL, 'metro', 'Transportation', 'global_seed'),
  (NULL, 'flight', 'Transportation', 'global_seed'),
  (NULL, 'airport', 'Transportation', 'global_seed'),
  (NULL, 'airline', 'Transportation', 'global_seed'),
  (NULL, 'parking', 'Transportation', 'global_seed'),
  (NULL, 'toll', 'Transportation', 'global_seed'),
  (NULL, 'gas', 'Transportation', 'global_seed'),
  (NULL, 'fuel', 'Transportation', 'global_seed'),
  (NULL, '车费', 'Transportation', 'global_seed'),
  (NULL, '乘坐', 'Transportation', 'global_seed'),
  (NULL, '班车', 'Transportation', 'global_seed'),
  (NULL, '高铁', 'Transportation', 'global_seed'),
  (NULL, '火车票', 'Transportation', 'global_seed'),
  (NULL, '飞机票', 'Transportation', 'global_seed'),
  (NULL, '机票', 'Transportation', 'global_seed'),
  (NULL, '停泊费', 'Transportation', 'global_seed'),
  (NULL, '汽油', 'Transportation', 'global_seed'),
  (NULL, '饿了么', 'Eating Out', 'global_seed'),
  (NULL, '瑞幸咖啡', 'Eating Out', 'global_seed'),
  (NULL, 'luckin coffee', 'Eating Out', 'global_seed'),
  (NULL, '汉堡王', 'Eating Out', 'global_seed'),
  (NULL, 'BURGER KING', 'Eating Out', 'global_seed'),
  (NULL, '味千拉面', 'Eating Out', 'global_seed'),
  (NULL, '杨国福麻辣烫', 'Eating Out', 'global_seed'),
  (NULL, '张亮麻辣烫', 'Eating Out', 'global_seed'),
  (NULL, '和府捞面', 'Eating Out', 'global_seed'),
  (NULL, '遇见小面', 'Eating Out', 'global_seed'),
  (NULL, '紫燕百味鸡', 'Eating Out', 'global_seed'),
  (NULL, '沙县小吃', 'Eating Out', 'global_seed'),
  (NULL, '太二酸菜鱼', 'Eating Out', 'global_seed'),
  (NULL, '正新鸡排', 'Eating Out', 'global_seed'),
  (NULL, '巴奴毛肚火锅', 'Eating Out', 'global_seed'),
  (NULL, '西贝莜面村', 'Eating Out', 'global_seed'),
  (NULL, '塔可贝尔', 'Eating Out', 'global_seed'),
  (NULL, '乡村基', 'Eating Out', 'global_seed'),
  (NULL, '大米先生', 'Eating Out', 'global_seed'),
  (NULL, '米村拌饭', 'Eating Out', 'global_seed'),
  (NULL, '永和大王', 'Eating Out', 'global_seed'),
  (NULL, '大娘水饺', 'Eating Out', 'global_seed'),
  (NULL, '袁记云饺', 'Eating Out', 'global_seed'),
  (NULL, '眉州东坡', 'Eating Out', 'global_seed'),
  (NULL, '南京大牌档', 'Eating Out', 'global_seed'),
  (NULL, '绿茶餐厅', 'Eating Out', 'global_seed'),
  (NULL, 'Manner咖啡', 'Eating Out', 'global_seed'),
  (NULL, 'Tims咖啡', 'Eating Out', 'global_seed'),
  (NULL, 'CoCo都可', 'Eating Out', 'global_seed'),
  (NULL, '茶颜悦色', 'Eating Out', 'global_seed'),
  (NULL, '库迪咖啡', 'Eating Out', 'global_seed'),
  (NULL, '蜜雪冰城', 'Eating Out', 'global_seed'),
  (NULL, 'McDonald''s', 'Eating Out', 'global_seed'),
  (NULL, '麦当劳', 'Eating Out', 'global_seed'),
  (NULL, '肯德基', 'Eating Out', 'global_seed'),
  (NULL, 'KFC', 'Eating Out', 'global_seed'),
  (NULL, '必胜客', 'Eating Out', 'global_seed'),
  (NULL, 'Pizza Hut', 'Eating Out', 'global_seed'),
  (NULL, '达美乐', 'Eating Out', 'global_seed'),
  (NULL, 'Domino''s', 'Eating Out', 'global_seed'),
  (NULL, '萨莉亚', 'Eating Out', 'global_seed'),
  (NULL, 'Saizeriya', 'Eating Out', 'global_seed'),
  (NULL, '瑞幸', 'Eating Out', 'global_seed'),
  (NULL, '星巴克', 'Eating Out', 'global_seed'),
  (NULL, '喜茶', 'Eating Out', 'global_seed'),
  (NULL, 'HEYTEA', 'Eating Out', 'global_seed'),
  (NULL, '霸王茶姬', 'Eating Out', 'global_seed'),
  (NULL, 'CHAGEE', 'Eating Out', 'global_seed'),
  (NULL, 'Mixue', 'Eating Out', 'global_seed'),
  (NULL, '蜜雪', 'Eating Out', 'global_seed'),
  (NULL, '茶百道', 'Eating Out', 'global_seed'),
  (NULL, '古茗', 'Eating Out', 'global_seed'),
  (NULL, '奈雪', 'Eating Out', 'global_seed'),
  (NULL, '沪上阿姨', 'Eating Out', 'global_seed'),
  (NULL, '书亦烧仙草', 'Eating Out', 'global_seed'),
  (NULL, '甜啦啦', 'Eating Out', 'global_seed'),
  (NULL, '益禾堂', 'Eating Out', 'global_seed'),
  (NULL, '1点点', 'Eating Out', 'global_seed'),
  (NULL, '一点点', 'Eating Out', 'global_seed'),
  (NULL, 'SUBWAY', 'Eating Out', 'global_seed'),
  (NULL, 'POPEYES', 'Eating Out', 'global_seed'),
  (NULL, '海底捞', 'Eating Out', 'global_seed'),
  (NULL, '吉野家', 'Eating Out', 'global_seed'),
  (NULL, '味千', 'Eating Out', 'global_seed'),
  (NULL, '真功夫', 'Eating Out', 'global_seed'),
  (NULL, '老娘舅', 'Eating Out', 'global_seed'),
  (NULL, '西贝', 'Eating Out', 'global_seed'),
  (NULL, '华莱士', 'Eating Out', 'global_seed'),
  (NULL, '德克士', 'Eating Out', 'global_seed'),
  (NULL, '塔斯汀', 'Eating Out', 'global_seed'),
  (NULL, '黄记煌', 'Eating Out', 'global_seed'),
  (NULL, '小肥羊', 'Eating Out', 'global_seed'),
  (NULL, '老乡鸡', 'Eating Out', 'global_seed'),
  (NULL, '杨国福', 'Eating Out', 'global_seed'),
  (NULL, '九毛九', 'Eating Out', 'global_seed'),
  (NULL, '呷哺呷哺', 'Eating Out', 'global_seed'),
  (NULL, '小龙坎', 'Eating Out', 'global_seed'),
  (NULL, '大龙燚', 'Eating Out', 'global_seed'),
  (NULL, '外婆家', 'Eating Out', 'global_seed'),
  (NULL, '费大厨', 'Eating Out', 'global_seed'),
  (NULL, '西少爷', 'Eating Out', 'global_seed'),
  (NULL, '兰熊鲜奶', 'Eating Out', 'global_seed'),
  (NULL, '巴奴', 'Eating Out', 'global_seed'),
  (NULL, 'Manner', 'Eating Out', 'global_seed'),
  (NULL, 'M Stand', 'Eating Out', 'global_seed'),
  (NULL, '库迪', 'Eating Out', 'global_seed'),
  (NULL, '蘇小柳', 'Eating Out', 'global_seed'),
  (NULL, '昆仑唐府', 'Eating Out', 'global_seed'),
  (NULL, '喝清喝理', 'Eating Out', 'global_seed'),
  (NULL, '正三熙', 'Eating Out', 'global_seed'),
  (NULL, '小满手工粉', 'Eating Out', 'global_seed'),
  (NULL, '卯时六点半', 'Eating Out', 'global_seed'),
  (NULL, '餐饮', 'Eating Out', 'global_seed'),
  (NULL, 'catering', 'Eating Out', 'global_seed'),
  (NULL, 'Meituan', 'Eating Out', 'global_seed'),
  (NULL, '美团', 'Eating Out', 'global_seed'),
  (NULL, 'restaurant', 'Eating Out', 'global_seed'),
  (NULL, 'cafe', 'Eating Out', 'global_seed'),
  (NULL, 'coffee', 'Eating Out', 'global_seed'),
  (NULL, 'café', 'Eating Out', 'global_seed'),
  (NULL, 'food delivery', 'Eating Out', 'global_seed'),
  (NULL, 'takeout', 'Eating Out', 'global_seed'),
  (NULL, 'takeaway', 'Eating Out', 'global_seed'),
  (NULL, 'order food', 'Eating Out', 'global_seed'),
  (NULL, 'menu', 'Eating Out', 'global_seed'),
  (NULL, 'dine', 'Eating Out', 'global_seed'),
  (NULL, 'snack', 'Eating Out', 'global_seed'),
  (NULL, 'noodle', 'Eating Out', 'global_seed'),
  (NULL, 'ramen', 'Eating Out', 'global_seed'),
  (NULL, 'sushi', 'Eating Out', 'global_seed'),
  (NULL, 'burger', 'Eating Out', 'global_seed'),
  (NULL, 'pizza', 'Eating Out', 'global_seed'),
  (NULL, 'taco', 'Eating Out', 'global_seed'),
  (NULL, 'kebab', 'Eating Out', 'global_seed'),
  (NULL, 'boba', 'Eating Out', 'global_seed'),
  (NULL, 'bubble tea', 'Eating Out', 'global_seed'),
  (NULL, '面馆', 'Eating Out', 'global_seed'),
  (NULL, '饭店', 'Eating Out', 'global_seed'),
  (NULL, '饮食', 'Eating Out', 'global_seed'),
  (NULL, '外卖', 'Eating Out', 'global_seed'),
  (NULL, '订餐', 'Eating Out', 'global_seed'),
  (NULL, '小吃', 'Eating Out', 'global_seed'),
  (NULL, '烧烤', 'Eating Out', 'global_seed'),
  (NULL, '火锅', 'Eating Out', 'global_seed'),
  (NULL, '粥店', 'Eating Out', 'global_seed'),
  (NULL, '炸鸡', 'Eating Out', 'global_seed'),
  (NULL, '淘宝闪购', 'Shopping', 'global_seed'),
  (NULL, '淘宝平台', 'Shopping', 'global_seed'),
  (NULL, '淘天物流', 'Shopping', 'global_seed'),
  (NULL, '京东物流', 'Shopping', 'global_seed'),
  (NULL, '京东秒送', 'Shopping', 'global_seed'),
  (NULL, '小米有品', 'Shopping', 'global_seed'),
  (NULL, '网易严选', 'Shopping', 'global_seed'),
  (NULL, '淘宝', 'Shopping', 'global_seed'),
  (NULL, 'Taobao', 'Shopping', 'global_seed'),
  (NULL, '天猫', 'Shopping', 'global_seed'),
  (NULL, '京东', 'Shopping', 'global_seed'),
  (NULL, 'JD.com', 'Shopping', 'global_seed'),
  (NULL, '拼多多', 'Shopping', 'global_seed'),
  (NULL, 'Pinduoduo', 'Shopping', 'global_seed'),
  (NULL, '得物', 'Shopping', 'global_seed'),
  (NULL, 'Dewu', 'Shopping', 'global_seed'),
  (NULL, '闲鱼', 'Shopping', 'global_seed'),
  (NULL, '1688', 'Shopping', 'global_seed'),
  (NULL, '唯品会', 'Shopping', 'global_seed'),
  (NULL, '抖音', 'Shopping', 'global_seed'),
  (NULL, '快手', 'Shopping', 'global_seed'),
  (NULL, '小红书', 'Shopping', 'global_seed'),
  (NULL, '京喜', 'Shopping', 'global_seed'),
  (NULL, '菜鸟', 'Shopping', 'global_seed'),
  (NULL, '名创优品', 'Shopping', 'global_seed'),
  (NULL, 'MINISO', 'Shopping', 'global_seed'),
  (NULL, '无印良品', 'Shopping', 'global_seed'),
  (NULL, 'MUJI', 'Shopping', 'global_seed'),
  (NULL, '优衣库', 'Shopping', 'global_seed'),
  (NULL, '泡泡玛特', 'Shopping', 'global_seed'),
  (NULL, '迪卡侬', 'Shopping', 'global_seed'),
  (NULL, '宜家家居', 'Shopping', 'global_seed'),
  (NULL, '宜家', 'Shopping', 'global_seed'),
  (NULL, '全棉时代', 'Shopping', 'global_seed'),
  (NULL, '孩子王', 'Shopping', 'global_seed'),
  (NULL, '苏宁易购', 'Shopping', 'global_seed'),
  (NULL, '苏宁', 'Shopping', 'global_seed'),
  (NULL, '国美电器', 'Shopping', 'global_seed'),
  (NULL, '国美', 'Shopping', 'global_seed'),
  (NULL, '万达影城', 'Shopping', 'global_seed'),
  (NULL, '万达', 'Shopping', 'global_seed'),
  (NULL, '中免日上', 'Shopping', 'global_seed'),
  (NULL, '中免', 'Shopping', 'global_seed'),
  (NULL, '杜福睿', 'Shopping', 'global_seed'),
  (NULL, '杂物社', 'Shopping', 'global_seed'),
  (NULL, '屈臣氏', 'Shopping', 'global_seed'),
  (NULL, '万宁', 'Shopping', 'global_seed'),
  (NULL, '绿联', 'Shopping', 'global_seed'),
  (NULL, 'KKV', 'Shopping', 'global_seed'),
  (NULL, '小米之家', 'Shopping', 'global_seed'),
  (NULL, '小米', 'Shopping', 'global_seed'),
  (NULL, '华为', 'Shopping', 'global_seed'),
  (NULL, '苹果', 'Shopping', 'global_seed'),
  (NULL, 'NIKE', 'Shopping', 'global_seed'),
  (NULL, 'nike', 'Shopping', 'global_seed'),
  (NULL, 'Adidas', 'Shopping', 'global_seed'),
  (NULL, 'adidas', 'Shopping', 'global_seed'),
  (NULL, 'ZARA', 'Shopping', 'global_seed'),
  (NULL, 'zara', 'Shopping', 'global_seed'),
  (NULL, 'H&M', 'Shopping', 'global_seed'),
  (NULL, 'h&m', 'Shopping', 'global_seed'),
  (NULL, 'Forever 21', 'Shopping', 'global_seed'),
  (NULL, 'ASOS', 'Shopping', 'global_seed'),
  (NULL, 'Uniqlo', 'Shopping', 'global_seed'),
  (NULL, 'uniqlo', 'Shopping', 'global_seed'),
  (NULL, 'GAP', 'Shopping', 'global_seed'),
  (NULL, 'SHEIN', 'Shopping', 'global_seed'),
  (NULL, 'Gucci', 'Shopping', 'global_seed'),
  (NULL, 'LV', 'Shopping', 'global_seed'),
  (NULL, 'Prada', 'Shopping', 'global_seed'),
  (NULL, 'Burberry', 'Shopping', 'global_seed'),
  (NULL, 'Coach', 'Shopping', 'global_seed'),
  (NULL, 'Alexander McQueen', 'Shopping', 'global_seed'),
  (NULL, 'Balenciaga', 'Shopping', 'global_seed'),
  (NULL, 'Dior', 'Shopping', 'global_seed'),
  (NULL, 'Fendi', 'Shopping', 'global_seed'),
  (NULL, 'Hermes', 'Shopping', 'global_seed'),
  (NULL, 'Versace', 'Shopping', 'global_seed'),
  (NULL, 'Valentino', 'Shopping', 'global_seed'),
  (NULL, 'Armani', 'Shopping', 'global_seed'),
  (NULL, 'Tommy Hilfiger', 'Shopping', 'global_seed'),
  (NULL, 'Calvin Klein', 'Shopping', 'global_seed'),
  (NULL, 'Ralph Lauren', 'Shopping', 'global_seed'),
  (NULL, 'Lacoste', 'Shopping', 'global_seed'),
  (NULL, 'champion', 'Shopping', 'global_seed'),
  (NULL, 'Champion', 'Shopping', 'global_seed'),
  (NULL, 'Reebok', 'Shopping', 'global_seed'),
  (NULL, 'Puma', 'Shopping', 'global_seed'),
  (NULL, 'New Balance', 'Shopping', 'global_seed'),
  (NULL, 'Converse', 'Shopping', 'global_seed'),
  (NULL, 'Vans', 'Shopping', 'global_seed'),
  (NULL, 'Samsung', 'Shopping', 'global_seed'),
  (NULL, 'samsung', 'Shopping', 'global_seed'),
  (NULL, 'LG', 'Shopping', 'global_seed'),
  (NULL, 'Sony', 'Shopping', 'global_seed'),
  (NULL, 'Panasonic', 'Shopping', 'global_seed'),
  (NULL, 'Intel', 'Shopping', 'global_seed'),
  (NULL, 'Nvidia', 'Shopping', 'global_seed'),
  (NULL, 'AMD', 'Shopping', 'global_seed'),
  (NULL, 'Razer', 'Shopping', 'global_seed'),
  (NULL, 'Logitech', 'Shopping', 'global_seed'),
  (NULL, 'SteelSeries', 'Shopping', 'global_seed'),
  (NULL, 'Corsair', 'Shopping', 'global_seed'),
  (NULL, 'ASUS', 'Shopping', 'global_seed'),
  (NULL, 'Acer', 'Shopping', 'global_seed'),
  (NULL, 'Lenovo', 'Shopping', 'global_seed'),
  (NULL, 'Dell', 'Shopping', 'global_seed'),
  (NULL, 'HP', 'Shopping', 'global_seed'),
  (NULL, 'Microsoft', 'Shopping', 'global_seed'),
  (NULL, 'Canon', 'Shopping', 'global_seed'),
  (NULL, 'Nikon', 'Shopping', 'global_seed'),
  (NULL, 'Sony', 'Shopping', 'global_seed'),
  (NULL, 'GoPro', 'Shopping', 'global_seed'),
  (NULL, 'DJI', 'Shopping', 'global_seed'),
  (NULL, 'iPhone', 'Shopping', 'global_seed'),
  (NULL, 'iPad', 'Shopping', 'global_seed'),
  (NULL, 'MacBook', 'Shopping', 'global_seed'),
  (NULL, 'AirPods', 'Shopping', 'global_seed'),
  (NULL, 'Apple Watch', 'Shopping', 'global_seed'),
  (NULL, 'watch', 'Shopping', 'global_seed'),
  (NULL, 'camera', 'Shopping', 'global_seed'),
  (NULL, 'drone', 'Shopping', 'global_seed'),
  (NULL, 'headphone', 'Shopping', 'global_seed'),
  (NULL, 'earphone', 'Shopping', 'global_seed'),
  (NULL, 'laptop', 'Shopping', 'global_seed'),
  (NULL, 'monitor', 'Shopping', 'global_seed'),
  (NULL, 'keyboard', 'Shopping', 'global_seed'),
  (NULL, 'mouse', 'Shopping', 'global_seed'),
  (NULL, 'charger', 'Shopping', 'global_seed'),
  (NULL, 'cable', 'Shopping', 'global_seed'),
  (NULL, 'battery', 'Shopping', 'global_seed'),
  (NULL, 'router', 'Shopping', 'global_seed'),
  (NULL, 'speaker', 'Shopping', 'global_seed'),
  (NULL, 'microphone', 'Shopping', 'global_seed'),
  (NULL, 'product', 'Shopping', 'global_seed'),
  (NULL, 'item', 'Shopping', 'global_seed'),
  (NULL, 'clothing', 'Shopping', 'global_seed'),
  (NULL, 'apparel', 'Shopping', 'global_seed'),
  (NULL, 'shoes', 'Shopping', 'global_seed'),
  (NULL, 'shoe', 'Shopping', 'global_seed'),
  (NULL, 'outfit', 'Shopping', 'global_seed'),
  (NULL, 'dress', 'Shopping', 'global_seed'),
  (NULL, 'pants', 'Shopping', 'global_seed'),
  (NULL, 'shirt', 'Shopping', 'global_seed'),
  (NULL, 'jacket', 'Shopping', 'global_seed'),
  (NULL, 'gadget', 'Shopping', 'global_seed'),
  (NULL, 'device', 'Shopping', 'global_seed'),
  (NULL, 'toy', 'Shopping', 'global_seed'),
  (NULL, 'toy store', 'Shopping', 'global_seed'),
  (NULL, 'pet store', 'Shopping', 'global_seed'),
  (NULL, 'pet', 'Shopping', 'global_seed'),
  (NULL, 'book', 'Shopping', 'global_seed'),
  (NULL, 'bookstore', 'Shopping', 'global_seed'),
  (NULL, 'office supplies', 'Shopping', 'global_seed'),
  (NULL, 'office', 'Shopping', 'global_seed'),
  (NULL, 'craft', 'Shopping', 'global_seed'),
  (NULL, '服装', 'Shopping', 'global_seed'),
  (NULL, '衣服', 'Shopping', 'global_seed'),
  (NULL, '鞋子', 'Shopping', 'global_seed'),
  (NULL, '玩具', 'Shopping', 'global_seed'),
  (NULL, '宠物', 'Shopping', 'global_seed'),
  (NULL, '书籍', 'Shopping', 'global_seed'),
  (NULL, '图书', 'Shopping', 'global_seed'),
  (NULL, '办公', 'Shopping', 'global_seed'),
  (NULL, '手工', 'Shopping', 'global_seed'),
  (NULL, '**', 'Shopping', 'global_seed'),
  (NULL, '华润', 'Groceries', 'global_seed'),
  (NULL, '国际旅行卫生保健', 'Utilities & Services', 'global_seed'),
  (NULL, '一网通办', 'Utilities & Services', 'global_seed'),
  (NULL, '国家电网', 'Utilities & Services', 'global_seed'),
  (NULL, '南方电网', 'Utilities & Services', 'global_seed'),
  (NULL, '中国移动', 'Utilities & Services', 'global_seed'),
  (NULL, '中国联通', 'Utilities & Services', 'global_seed'),
  (NULL, '中国电信', 'Utilities & Services', 'global_seed'),
  (NULL, 'China Mobile', 'Utilities & Services', 'global_seed'),
  (NULL, '中石化', 'Utilities & Services', 'global_seed'),
  (NULL, '中石油', 'Utilities & Services', 'global_seed'),
  (NULL, 'Sinopec', 'Utilities & Services', 'global_seed'),
  (NULL, 'PetroChina', 'Utilities & Services', 'global_seed'),
  (NULL, '申通快递', 'Utilities & Services', 'global_seed'),
  (NULL, '中通快递', 'Utilities & Services', 'global_seed'),
  (NULL, '圆通速递', 'Utilities & Services', 'global_seed'),
  (NULL, '韵达快递', 'Utilities & Services', 'global_seed'),
  (NULL, '极兔速递', 'Utilities & Services', 'global_seed'),
  (NULL, '德邦快递', 'Utilities & Services', 'global_seed'),
  (NULL, '邮政EMS', 'Utilities & Services', 'global_seed'),
  (NULL, '顺丰', 'Utilities & Services', 'global_seed'),
  (NULL, '中通', 'Utilities & Services', 'global_seed'),
  (NULL, '圆通', 'Utilities & Services', 'global_seed'),
  (NULL, '韵达', 'Utilities & Services', 'global_seed'),
  (NULL, '极兔', 'Utilities & Services', 'global_seed'),
  (NULL, '德邦', 'Utilities & Services', 'global_seed'),
  (NULL, 'EMS', 'Utilities & Services', 'global_seed'),
  (NULL, '共享按摩椅', 'Utilities & Services', 'global_seed'),
  (NULL, '爱奇艺', 'Utilities & Services', 'global_seed'),
  (NULL, '腾讯视频', 'Utilities & Services', 'global_seed'),
  (NULL, '优酷', 'Utilities & Services', 'global_seed'),
  (NULL, '芒果TV', 'Utilities & Services', 'global_seed'),
  (NULL, '汽水音乐', 'Utilities & Services', 'global_seed'),
  (NULL, '哔哩哔哩', 'Utilities & Services', 'global_seed'),
  (NULL, 'B站', 'Utilities & Services', 'global_seed'),
  (NULL, '网易', 'Utilities & Services', 'global_seed'),
  (NULL, 'subscription', 'Utilities & Services', 'global_seed'),
  (NULL, 'monthly fee', 'Utilities & Services', 'global_seed'),
  (NULL, 'annual fee', 'Utilities & Services', 'global_seed'),
  (NULL, 'renewal', 'Utilities & Services', 'global_seed'),
  (NULL, 'service charge', 'Utilities & Services', 'global_seed'),
  (NULL, 'membership', 'Utilities & Services', 'global_seed'),
  (NULL, 'premium', 'Utilities & Services', 'global_seed'),
  (NULL, 'bill', 'Utilities & Services', 'global_seed'),
  (NULL, 'invoice', 'Utilities & Services', 'global_seed'),
  (NULL, 'service', 'Utilities & Services', 'global_seed'),
  (NULL, '续费', 'Utilities & Services', 'global_seed'),
  (NULL, '会费', 'Utilities & Services', 'global_seed'),
  (NULL, '月费', 'Utilities & Services', 'global_seed'),
  (NULL, '年费', 'Utilities & Services', 'global_seed'),
  (NULL, '服务费', 'Utilities & Services', 'global_seed'),
  (NULL, '订阅', 'Utilities & Services', 'global_seed'),
  (NULL, '会员', 'Utilities & Services', 'global_seed'),
  (NULL, 'transfer', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'Transfer', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'p2p', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'P2P', 'Transfers & Gifts', 'global_seed'),
  (NULL, '个人收款', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'send money', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'payment', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'remittance', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'gift', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'present', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'tip', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'gratuity', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'allowance', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'personal loan', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'reimbursement', 'Transfers & Gifts', 'global_seed'),
  (NULL, '汇款', 'Transfers & Gifts', 'global_seed'),
  (NULL, '红包', 'Transfers & Gifts', 'global_seed'),
  (NULL, '礼物', 'Transfers & Gifts', 'global_seed'),
  (NULL, '赏金', 'Transfers & Gifts', 'global_seed'),
  (NULL, '补贴', 'Transfers & Gifts', 'global_seed'),
  (NULL, '报销', 'Transfers & Gifts', 'global_seed'),
  (NULL, '打赏', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'Bank of China', 'Transfers & Gifts', 'global_seed'),
  (NULL, '中国银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '中国工商银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '工商银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '中国农业银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '农业银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '中国建设银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '建设银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '交通银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '中信银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '招商银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '浦发银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '民生银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '平安银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '兴业银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '光大银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '华夏银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '北京银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '上海银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '深圳发展银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '深圳银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '南京银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '杭州银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '宁波银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '温州银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '成都银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '西安银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '重庆银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '武汉银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '郑州银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '邮储银行', 'Transfers & Gifts', 'global_seed'),
  (NULL, '邮政储蓄', 'Transfers & Gifts', 'global_seed'),
  (NULL, '支付宝转账', 'Transfers & Gifts', 'global_seed'),
  (NULL, '微信转账', 'Transfers & Gifts', 'global_seed'),
  (NULL, '微信支付', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'alipay', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'wechat', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'withdrawal', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'Withdrawal', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'bank', 'Transfers & Gifts', 'global_seed'),
  (NULL, 'Bank', 'Transfers & Gifts', 'global_seed')
;

-- ========== FUNCTION: Initialize default categories for new user ==========
CREATE OR REPLACE FUNCTION initialize_default_categories()
RETURNS trigger AS $$
BEGIN
  -- Create the 7 default categories for this user
  INSERT INTO categories (user_id, name, is_catch_all, sort_order)
  VALUES
    (NEW.id, 'Food', false, 1),
    (NEW.id, 'Transport', false, 2),
    (NEW.id, 'Shopping', false, 3),
    (NEW.id, 'Entertainment', false, 4),
    (NEW.id, 'Health', false, 5),
    (NEW.id, 'Work', false, 6),
    (NEW.id, 'Other', true, 7);

  -- Initialize budget config for this user
  INSERT INTO budget_config (user_id, currency)
  VALUES (NEW.id, 'CNY');

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach the trigger to profiles
CREATE TRIGGER after_profile_created
  AFTER INSERT ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION initialize_default_categories();
